title: Jaehyeong Study Notes
description: NLP, Cognitive Science, HCI, and AI Interpretability
theme: just-the-docs

url: "https://JAEHYEONG8121.github.io"

aux_links:
  GitHub:
    - "https://github.com/JAEHYEONG8121"

color_scheme: light
